modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "discord4kjs"
version = "${version}"
displayName = "Discord4KJS"
authors = "Me!"
description = '''
Discord4J bindings for KubeJS. Create your own discord bots that run off Minecraft!
'''
logoFile = "pack.png"

[[dependencies.discord4kjs]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discord4kjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discord4kjs]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.discord4kjs]]
modId = "kubejs"
mandatory = true
versionRange = "[6.1,)"
ordering = "AFTER"
side = "BOTH"